### ISSUE TITLE
--export is deprecated and removed in newer versions of oc

### ISSUE THREAD

**Issue by psegedy** [bsquizz/ocdeployer#52]
On my fedora with oc v3.11.154 it still works with --export option, but with latest `oc` in `redhat-actions/oc-installer` gh action I'm getting

```
 2021-01-25 09:53:05     INFO [main           ] Importing secret 'quay-cloudservices-pull' from project 'secrets'
2021-01-25 09:53:05     INFO [pid-3123       ]  |stderr| Error: unknown flag: --export
2021-01-25 09:53:05     INFO [pid-3123       ]  |stderr| See 'oc get --help' for usage.
2021-01-25 09:53:05    ERROR [main           ] Hit fatal error!  Aborting.
```
caused by 
https://github.com/bsquizz/ocdeployer/blob/650d1495bcc7e35b16185acd3de56976d5a36f1c/ocdeployer/secrets.py#L55

**Comment by bsquizz** [comment]
Hmm... at some point, `oc export` was deprecated and moved to `oc get --export` in newer versions of `oc`.

What is the version of `oc` being used in gh actions?

**Comment by psegedy** [comment]
I don't know it used `latest` because they have an outdated example https://github.com/redhat-actions/oc-installer#example, I had to set `oc_version` not `version`, maybe it used v4 client. Anyway, I found this [commit](https://github.com/kubernetes/website/commit/a98753cfe9c2c59a6525731e7af6931fe382afd9/) in kubernetes docs change that removes `--export`

I pinned the `oc_version` in gh action and it is fine now. IMHO, no change is needed as long as fedora has the older client, or if you want to support a v4 client.

**Comment by bsquizz** [comment]
Seems like we may need to start using simply 'oc get' and then removing
cluster-specific info manually :(

https://stackoverflow.com/questions/61392206/kubectl-export-is-deprecated-any-alternative

For example here's an approach sysdig took in one of their scripts:
https://github.com/draios/sysdig-cloud-scripts/pull/128/files

I have a new library started to split out the "oc" helper utilities that I
am intending to migrate ocdeployer over to:
https://github.com/bsquizz/ocviapy

I think the solution would be to add an 'export' helper function into
ocviapy
